version: "3.2"
services:
  server:
    build: .
    image: chsheet_server
    ports:
    - target: 8080
      published: 80
      protocol: tcp
      mode: host
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: example
