version: "3.2"
services:
  database:
    image: postgres:12
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=chsheet_db
    healthcheck:
      # note -U must be the same as POSTGRES_USER
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 1s
      retries: 5
  server:
    build: .
    depends_on:
      - database
    image: chsheet_server
    ports:
      - target: 8080
        published: 80
        protocol: tcp
    environment:
      - PGHOST=database
      - PGPORT=5432
      - PGDATABASE=chsheet_db
      - PGUSER=postgres
      - PGPASSWORD=password
