version: "3.2"
services:
  database:
    build: ./database
    image: chsheet_postgres
    restart: always
  server:
    build: .
    depends_on:
      - database
    image: chsheet_server
    ports:
      - target: 8080
        published: 80
        protocol: tcp
        mode: host
